version: "3" # optional since v1.27.0
services:
  BDD:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /home/xwdrblue/database/datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789 

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: 172.17.0.1
    depends_on:
      - BDD
  backend:
    image: backend_2r
    ports:
      - 5000:5000
    depends_on:
      - BDD
  Apache_react:
    image: apache_2r
    volumes:
      - /media/xwdrblue/Disque/projet_2r/server/cert:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - backend
